# Generated by Django 6.1 on 2026-09-11 00:05

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_account_name_per_holder',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='balance',
            new_name='opening_balance',
        ),
        migrations.AddField(
            model_name='account',
            name='opening_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('account_name', 'account_holder'), name='unique_account_name_per_holder'),
        ),
    ]
