# Generated by Django 6.1 on 2026-09-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_account_unique_account_name_per_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='Internal', max_length=10),
        ),
    ]
