# Generated by Django 6.1 on 2026-09-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='opening_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='opening_date',
        ),
    ]
