# Generated by Django 6.1 on 2026-09-11 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_account_type'),
        ('transactions', '0002_remove_transaction_sent_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='accounts.account'),
            preserve_default=False,
        ),
    ]
